# Build step #1: build the React front end
FROM node:16 as build-step
WORKDIR /client
ENV PATH /client/node_modules/.bin:$PATH
COPY package.json package-lock.json tsconfig.json ./
COPY ./src ./src
COPY ./public ./public
COPY ./types ./types

RUN npm install
RUN npm run build

# Build step #2: build an nginx container
FROM nginx
COPY --from=build-step /client/build /usr/share/nginx/html
COPY ./deployment/nginx.default.conf /etc/nginx/conf.d/default.conf