services:
  client:
    # build:
    #   context: ./client
    #   dockerfile: Dockerfile.client
    # image: client
    image: 494836267659.dkr.ecr.us-west-1.amazonaws.com/flea-market-client
    ports:
      - "80:80"
    depends_on:
      - server
  server:
    # build:
    #   context: ./server
    #   dockerfile: Dockerfile.server
    # image: server
    image: 494836267659.dkr.ecr.us-west-1.amazonaws.com/flea-market-server



  
