services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    image: client
    #image: 494836267659.dkr.ecr.us-west-1.amazonaws.com/flea-market-client2
    ports:
      - "3000:80"
      #- "80:80"
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    image: server
    #image: 494836267659.dkr.ecr.us-west-1.amazonaws.com/flea-market-server2
    # ports:
    #   - 5000:5000


  
