export enum GameStateEnum {
  INIT = "init",
  BUY_SELL_JET = "buySellJet",
  INSTRUCTIONS = "instructions",
  JET = "jet",
  BUY = "buy",
}

export enum FleaMarketFunction {
  RETRIEVE_GAME_STATE = "RETRIEVE_GAME_STATE",
  CHECK_MAXIMUM_BUY = "CHECK_MAXIMUM_BUY",
  CHANGE_WALLET = "CHANGE_WALLET",
  SET_PRICES = "SET_PRICES",
  GET_PRICES = "GET_PRICES",
  BUY_SELL_JET = "BUY_SELL_JET",
  JET = "JET",
  CHANGE_LOCATION = "CHANGE_LOCATION",
  INSTRUCTIONS = "INSTRUCTIONS",
  GET_INSTRUCTIONS = "GET_INSTRUCTIONS",
  INSTRUCTIONS_CONTINUE = "INSTRUCTIONS_CONTINUE",
  GET_STASH = "GET_STASH",
  GET_TRENCH_COAT = "GET_TRENCH_COAT",
  GET_LOCATION = "GET_LOCATION",
  NEW_GAME = "NEW_GAME",
  GET_DAY = "GET_DAY",
  BUY_ITEM = "BUY_ITEM",
}
