FROM python:3.9.7
WORKDIR /server

COPY ./game_files ./game_files
COPY app.py requirements.txt ./
RUN pip3 install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "app:app"]